spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

jwt:
  client:
    id: kotlinstrap
    secret: yourSecretHere
    signing-key: yourSigningKey
    access-token-validity: 43200
    authorized-grant-types: password, authorization_code, refresh_token
    refresh-token-validity: 2592000

logging:
  level:
    org.springframework.security: DEBUG
---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlinstrap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver