spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlinstrap
    username: postgres
    password: postgres

kotlinstrap:
  app:
    jwtSecret: 59fedfab-9fa7-4a33-9ea0-c76e7729009a
    jwtExpirationMs: 86400000

